apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: b9h9gaq1f-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/b9h9gaq1f-java-quarkus-gitops